### ISSUE TITLE
I have to wake buttons up each time, is that because of the timeout?

### ISSUE THREAD

**Issue by shanness** [hufftheweevil/node-red-contrib-flic-buttons#1]
Hi,

Thanks very much for this project BTW!

So, it's working, except if I haven't used a button for a while, the first click gets ignored.  Is that because of the timeout?  Is there any way to fix that without draining the battery?

It's also a bit flakey.  Like if I press and hold, I don't get it triggering in node red sometimes, but then I press the button again, and both events come through.

**Comment by shanness** [comment]
Just done some more testing.  I did a single click.  Nothing.  Did a click and hold, nothing.   Did another single click and it triggered the double click :(

**Comment by hufftheweevil** [comment]
I just added a small feature that shows the most recent event as the status. Hope this will help with debugging.

As for your issue - I have, at times, had similar connection issues. 99% of the time it is related to the bluetooth connection between the button and `flicd. Occasionally I need to restart `flicd` (I have it running as a HA addon). That usually solves the problem.

To reference your question about the timeout/battery drain issue... unfortunately that's just how it has to be. Either keep the connection 100% alive and drain the battery. Or allow it to semi-disconnect and then immediately re-connect on usage. I mean it's a wonder that we have it working at all, really.

**Comment by shanness** [comment]
Hey @hufftheweevil thanks very much for the updated code.  It's all working much better now.  Not exactly sure why, but after trying to connect more of my flic's I realised it the BT adaptor on the back of my computer must be causing to much interferance with them (they worked if I moved them to within 1 or 2 meters).  Moved to the front USB slots, and everything seems to be working dandy :)

BTW, the upgrade cleared all the assigned events (single click etc).  Was easy to fix once I figured it out (and luckily had named to nodes clearly so knew what event they used to listen to).

Thanks again!  Fingers crossed I've finally got stabled flics (never worked that well through my phone).

**Comment by hufftheweevil** [comment]
Glad it all worked out.

I, too, used to never know if the button was actually going to work when I pressed it. But I'm happy to say that that's not the case anymore. I think my buttons work as expected about 99.9% of the time now. 1/1000 is good enough for me.

**Comment by shanness** [comment]
Thanks so much for this.  Your fix and me moving the dongle onto a USB extension cable and putting it up above all monitors and computers has made it spot on, works perfectly now (and has been for months).  Just leaving this here for anyone else.  My dongle (from lsusb)
ASUSTek Computer, Inc. Broadcom BCM20702A0 Bluetooth
is pretty sensitive to positioning, get it away from metal and interference and things should work better.
